apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: name
  name: name
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    mode: name
  type: ClusterIP
