apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
    version: v1
  name: sentences-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
      version: v1
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
        version: v1
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: sentences
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: sentence
  name: sentences
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    mode: sentence
  type: NodePort

