apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: name
    version: v3
  name: name-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: name
      version: v3
  template:
    metadata:
      labels:
        app: sentences
        mode: name
        version: v3
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: name
        ports:
          - containerPort: 5000
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_NAMES"
          value: "Athos (v3),Porthos (v3),Aramis (v3),d'Artagnan (v3)"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"