apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
    version: v2
  name: sentences-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
      version: v2
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
        version: v2
    spec:
      containers:
      - image: praqma/istio-sentences:v1
        name: sentences
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
        - name: "SENTENCE_AUTH_BUG_PROBABILITY"
          value: "0.2"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"